### ISSUE TITLE
Screen usage suddenly bursts to ~16 kilodays

### ISSUE THREAD

**Issue by Self-Perfection** [g7/jolla-settings-screenmonitor#2]
After a short period after reset I always end up with statistics values like this
![20150115162021](https://cloud.githubusercontent.com/assets/3757038/5759540/a7b795f8-9cdf-11e4-8dab-9db9eabc2da7.png)

After reboot and reset stats in app after several hours I get similar stats
I use SailfishOS 1.1.1.27 (Vaarainjärvi)

**Comment by g7** [comment]
Hello,

thank you for the bug report.

I have noticed this too starting with 1.1.0.x Uitukka. It seems that the internal timer starts before the actual time is set during boot - which is strange because the Jolla should have a real time clock, but whatever - and thus it starts at 1970-01-01.

I'll have a look though, didn't have much time to look at it before but I agree that this bug is pretty annoying.


Regards,
Eugenio

**Comment by g7** [comment]
Fixed in 1.0.2-1.


Eugenio
